name: build-mat-flashcard
env:
  TOKEN_COMMIT: ${{secrets.TOKEN_COMMIT}}
  USER_NAME: mrbrique
  USER_EMAIL: ${{secrets.USER_EMAIL}}
on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]
jobs:
  ng-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout material-flashacard
        uses: actions/checkout@v2

      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm package
        run: npm install

      - name: Install @angular/cli
        run: npm install -g @angular/cli

      - name: Build angular app
        run: ng build

      - name: Commit to material-flashcard.github.io
        run: |
          cd ./dist
          git init -b main
          echo git init completed
          git config --local user.name $USER_NAME
          echo git config user.name completed
          git config --local user.email $USER_EMAIL
          echo git config user.email completed
          echo local Git repository config completed
          git status
          git remote add origin https://$TOKEN_COMMIT@github.com/material-flashcard/material-flashcard.github.io.git
          git checkout -b main
          git add --all
          git commit -m "Deploy to Github pages"
          git push origin main -f
