name: build-mat-flashcard
env:
  TOKEN_COMMIT: ${{ secrets.TOKEN_COMMIT }}
  USER_NAME: mrbrique
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  DIST_PATH: ./gh-pages/
on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]
jobs:
  ng-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout material-flashacard
        uses: actions/checkout@v2

      - name: Checkout material-flashcard.github.io
        uses: actions/checkout@v2
        with:
          repository: 'material-flashcard/material-flashcard.github.io'
          path: $DIST_PATH

      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm package
        run: npm install

      - name: Install @angular/cli
        run: npm install -g @angular/cli

      - name: Build material-flashacard
        run: ng build

      - name: Commit to material-flashcard.github.io
        run: |
          cp -a ./dist/material-flashcard/. $DIST_PATH
          cd $DIST_PATH
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          echo local Git repository config completed
          git status
          git checkout -b main
          git add --all
          git commit -m "Deploy to Github pages by build-mat-flashcard"
          git push origin main -f
